name: PyTorch Bisect

on:
  workflow_dispatch:
    inputs:
      benchmark:
        description: Benchmark to bisect
        required: true
        type: choice
        default: inductor
        options:
          - inductor
      type:
        description: Bisect type
        required: true
        type: choice
        default: performance
        options:
          - functional
          - performance
      runner:
        description: Hardware runner
        required: true
        type: choice
        default: linux.dgx.b200
        options:
          - linux.dgx.b200
          - linux.aws.h100
      command_arguments:
        description: Command arguments
        required: true
        type: string
        default: ""
      good_commit:
        description: Last known good PyTorch commit
        required: true
        type: string
      bad_commit:
        description: First known bad PyTorch commit
        required: true
        type: string

jobs:
  bisect:
    name: Run PyTorch Bisect
    runs-on: ${{ inputs.runner }}
    env:
      WORKSPACE_DIR: ${{ github.workspace }}
      GOOD_COMMIT: ${{ inputs.good_commit }}
      BAD_COMMIT: ${{ inputs.bad_commit }}
      PYTORCH_SRC_DIR: ${{ github.workspace }}/pytorch
      PYTORCH_REPO: https://github.com/pytorch/pytorch.git
      FUNCTIONAL: ${{ inputs.type == 'functional' && '1' || '0' }}
      REPRO_CMDLINE: ${{ inputs.command_arguments }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout tritonparse
        uses: actions/checkout@v4
        with:
          repository: pytorch-labs/tritonparse
          path: tritonparse
          ref: xz9/add-torch-bisect

      - name: Install tritonparse
        shell: bash
        run: |
          pip install -e tritonparse

      - name: Run PyTorch bisect
        shell: bash
        run: |
          bash .github/scripts/bisect/run.sh
